Loops
itstep-prepod/homework pull request #107
Opened 2022-07-19 13:52 UTC by Eughe

Homework Loops

2022-07-26 17:28 UTC, itstep-prepod requested changes

2022-07-26 17:28 UTC, itstep-prepod commented on Евгений Ермаркевич/loops/hw_loops.js
> +//     } else { for ( ; userNumber <= 0; userNumber++) {
поправить отступы

2022-07-26 17:28 UTC, itstep-prepod commented on Евгений Ермаркевич/loops/hw_loops.js
> +//         } else if (userNumber < 0) { negativeNumber++;
отступы!!!

2022-07-26 17:28 UTC, itstep-prepod commented on Евгений Ермаркевич/loops/hw_loops.js
> +//         } else if (userNumber < 0) { negativeNumber++;
и переносы строк!

2022-08-01 18:34 UTC, Eughe commented
Исправлено форматирование

2022-08-21 16:07 UTC, merged