homework loop
itstep-prepod/homework pull request #110
Opened 2022-07-19 16:57 UTC by Xenia-Nova

наконец  то она прилетит НОРМАЛЬНАЯ!

2022-07-26 17:35 UTC, itstep-prepod requested changes

2022-07-26 17:35 UTC, itstep-prepod commented on Xenia Bulanova/condirional/array.js
> +//  len += 2;
отступы!

2022-07-26 17:35 UTC, itstep-prepod commented on Xenia Bulanova/condirional/array.js
> +// let maxValue = 0;
это значение не может быть 0, тк такого значения не существует в массиве

2022-07-26 17:35 UTC, itstep-prepod commented on Xenia Bulanova/condirional/loops.js
> +//   formatNumber > 0
мы используем значение возвращаемое тернарником ? переписать в if () {}

2022-07-28 13:38 UTC, Xenia-Nova commented on Xenia Bulanova/condirional/array.js
> +// let maxValue = 0;
это начальное значение, в задании сказано про массив случайных чисел и мы не можем быть уверены что все они не равны "0"
Добавила некоторое дополнение в код

2022-07-28 13:38 UTC, Xenia-Nova commented on Xenia Bulanova/condirional/loops.js
> +//   formatNumber > 0
исправлено

2022-07-28 13:38 UTC, Xenia-Nova commented on Xenia Bulanova/condirional/array.js
> +//  len += 2;
исправлено

2022-08-21 16:09 UTC, itstep-prepod requested changes

2022-08-21 16:09 UTC, itstep-prepod commented on Xenia Bulanova/condirional/array.js
> +// let maxValue = 0;
мы не можем быть уверены что в массиве вообще есть ноль
если [-20, -15, -23, -6, -9]
в вашем случае максимальным будет 0, что не является верным ответом

2022-08-30 17:00 UTC, merged