add folder arrays and add tasks in task1
itstep-prepod/homework pull request #111
Opened 2022-07-21 11:08 UTC by Lev-Kin

studying the topic array

2022-07-26 17:40 UTC, itstep-prepod requested changes

2022-07-26 17:40 UTC, itstep-prepod commented on Олег Леванов/arrays/task1.js
> +// let max = 0;
max не может быть 0, тк в массиве вообще может не быть 0

2022-07-26 17:40 UTC, itstep-prepod commented on Олег Леванов/arrays/task1.js
> +//         console.log(i);
нужно выводить количество элементов а не сами элементы

2022-07-26 17:40 UTC, itstep-prepod commented on Олег Леванов/arrays/task1.js
> +// let maxEvenElement = 0;
не может быть 0

2022-07-26 17:40 UTC, itstep-prepod commented on Олег Леванов/arrays/task1.js
> +let max = Math.floor(100);
зачем здесь и выше округление ?

2022-07-27 10:41 UTC, Lev-Kin commented
Все замечания по заданиям были учтены и исправлены.

2022-08-21 16:11 UTC, merged