Arrays
itstep-prepod/homework pull request #118
Opened 2022-07-25 19:45 UTC by Eughe

Arrays homework

2022-07-26 18:03 UTC, itstep-prepod requested changes

2022-07-26 18:03 UTC, itstep-prepod commented on Евгений Ермаркевич/loops/hw_loops.js
> +//         } else if (userNumber < 0) { negativeNumber++;
отступы и переносы!

2022-08-01 19:58 UTC, Eughe commented
Исправлено в соответствии с замечаниями.

2022-08-21 16:14 UTC, itstep-prepod commented
нужно пофиксить конфликты

2022-08-30 17:01 UTC, closed without merging