add tasks.js in folder objects
itstep-prepod/homework pull request #135
Opened 2022-08-03 11:46 UTC by Lev-Kin

learning topic objects
solve tasks

2022-08-30 17:10 UTC, itstep-prepod requested changes

2022-08-30 17:10 UTC, itstep-prepod commented on Олег Леванов/objects/tasks.js
> +// for (let i = 0; i < arr.length; i++) {
избавиться от цикла, переписать чз метод массива

2022-08-30 17:10 UTC, itstep-prepod commented on Олег Леванов/objects/tasks.js
> +// for (let i = 0; i < arr.length; i++) {
метод!

2022-08-31 10:38 UTC, Lev-Kin commented
fix tasks

2022-10-04 15:58 UTC, merged