New branch
itstep-prepod/homework pull request #84
Opened 2022-07-11 17:43 UTC by Gena696

это первая домашняя. не получалось сбросить выдавала ошибки в git

2022-07-14 16:10 UTC, itstep-prepod commented
все еще конфликт

2022-07-16 08:42 UTC, Gena696 commented
Сделал в своей ветке newBranch --  git pull origin newBranch  и не прилетело мне изменений, которые нужно поправить.
я же "Резорвил"  и отправлял Вам уже.
сейчас еще раз Push сделаю

2022-07-16 11:24 UTC, itstep-prepod commented
git checkout master
git pull prepod master
git checkout newBranch
git merge master
резолвим конфликты
сохраняем файлы
коммитим
git push origin newBranch

2022-07-26 17:17 UTC, itstep-prepod requested changes

2022-07-26 17:17 UTC, itstep-prepod commented on Геннадий Сабадаш/conditionals/task3.js
> +    alert("Митрофан старше Федота на 5");
кто насколько старше должно вычисляться а не быть захардкоженым

2022-08-21 16:07 UTC, closed without merging